#cloud-config
users: # Collection bzw Sammlung von den Users
  - name: ubuntu # Der Benutzername des ersten also Standart benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # Sudo Regeln für diesen Benutzer
    groups: users, admin # Gruppen, zu denen der Benutzer gehört
    home: /home/ubuntu # Home-Verzeichnis des Benutzers
    shell: /bin/bash # Die Shell des Benutzers
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCChvm8U9bNWKZ2LBlRFvTQfLgdlNm5tKiA+GVqGzwN7hm6RsNp234mxQNSCoXfBkOYQObUxSJU12nnQaLUtm4ztrzwbU0Z6Dab8tqgt9k5QyuGmCRDSxVaK4skoWfoivGt/h9nqMqwroWVm11hTlLJfCQE8fj9bNUMye7KktxnaC8kgp5VfTCiH1aYPEaB4oyx8diToSNR3KERm5AZhIJ4SP8ho5YLRSaUaqIGvOxlCETov6p1p7lhQuZiMV/8YBzqsth7Jl8fNu7EaBerxJpRYSbWrSRAlJimOHTnJk6eaZLpkkRfvzERep046ze2BwuU56ZimMuWJAh/isjlwblP aws-key
    lock_passwd: false # Benutzer kann sich mit Passwort einloggen
    plain_text_passwd: 'password' # Der Hash für das Benutzer-Password       
ssh_pwauth: true # SSH Authentisierung einschalten
disable_root: false # Access für die Benutzter um auf den Root zuzugreifen
packages: # Eine Liste von Packages welche installiert werden
  - apache2 # Package für Webserver
  - curl # Package um zBs URL's aufzurufen
  - wget # Package um zBs HTML Files zu benutzen
  - php # Package um Server Tasks mit PHP zu automatisieren
  - libapache2-mod-php # Package mit PHP_Modul für Apache2
  - php-mysqli # Package mit MySQL-Modul für PHP
  - adminer # Package für Administrator um mit GUI die DB zu managen
write_files:
  - path: /var/www/html/info.php
    content: <?php phpinfo(); ?>  
    permission: '0644'
  - path: /var/www/html/db.php
    content: |
      <?php
        //database
        $servername = "100.27.38.195"
        $username = "admin";
        $password = "password";
        $dbname = "mysql";

        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) { 
          die("Connection failed: " . $conn->connect_error)
        }

        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
                echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
        //var_dump($result); 
      ?>  
    permission: '0644'
runcmd: 
 - "chown ubuntu:ubuntu /var/www/html/info.php /var/www/html/db.php"
 - "sudo a2enconf adminer"
 - "sudo systemctl restart apache2"

