#cloud-config
users: # Collection bzw Sammlung von den Users
  - name: ubuntu # Der Benutzername des ersten also Standart benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # Sudo Regeln für diesen Benutzer
    groups: users, admin # Gruppen, zu denen der Benutzer gehört
    home: /home/ubuntu # Home-Verzeichnis des Benutzers
    shell: /bin/bash # Die Shell des Benutzers
    lock_passwd: false # Benutzer kann sich mit Passwort einloggen
    plain_text_passwd: 'password' # Der Hash für das Benutzer-Password       
ssh_pwauth: true # SSH Authentisierung einschalten
disable_root: false # Access für die Benutzter um auf den Root zuzugreifen
packages: # Eine Liste von Packages welche installiert werden
  - mariadb-server
runcmd: 
  - "sudo sed -i's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf"

